enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1
build-mindetach-module = false
remove-rv-integrations-checks = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Morphe]
# enabled = false
app-name = "YouTube"
module-prop-name = "youtube-morphe-jhc"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
excluded-patches = "'Custom branding'"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "module"
arch = "arm64-v8a"
# version = "21.03.34"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
enabled = false
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Music-Morphe]
enabled = false
app-name = "Music"
module-prop-name = "music-morphe-jhc"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
excluded-patches = "'Custom branding'"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
module-prop-name = "youtube"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube'"
rv-brand = "ReVanced Extended"
build-mode = "module"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
version = "20.21.37"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Extended]
enabled = false
app-name = "Music"
module-prop-name = "music"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
excluded-patches = "'Custom branding name for YouTube Music' 'Custom branding icon for YouTube Music'"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
rv-brand = "ReVanced Extended"
build-mode = "module"
# version = "8.28.54"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
enabled = false
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[GooglePhotos]
enabled = false
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
